issues:
  # Print all issues reported by all linters.
  max-issues-per-linter: 0
  max-same-issues: 0

  # Don't ignore some of the issues that golangci-lint considers okay.
  # This includes documenting all exported entities.
  exclude-use-default: false

  exclude-rules:
    # Don't warn on unused parameters.
    # Parameter names are useful; replacing them with '_' is undesirable.
    - linters: [revive]
      text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'

    # staticcheck already has smarter checks for empty blocks.
    # revive's empty-block linter has false positives.
    # For example, as of writing this, the following is not allowed.
    #   for foo() { }
    - linters: [revive]
      text: 'empty-block: this block is empty, you can remove it'

linters-settings:
  decorder:
    dec-order:
      - type
      - const
      - var
      - func
  gci:
    sections:
      - default
      - prefix(github.com/badrchoubai)
    skip-generated: true
    custom-order: true
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style

linters:
  disable-all: true
  enable:
    - decorder
    - gci
    - gocritic
    - gosec
    - revive
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
output:
  # Make output more digestible with quickfix in vim/emacs/etc.
  sort-results: true
  print-issued-lines: false

run:
  concurrency: 8
  timeout: 5m

