basePath: /users/v1
host: 0.0.0.0:8080
info:
  contact: {}
  description: This user API is used to register and login users
  title: User API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: login user
  /register:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: register user
swagger: "2.0"
